### Unauthorized
GET http://localhost:8080/hello

### Test
GET http://localhost:8080/test


### Authentication
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
    "username":"grogu",
    "password":"password"
}

### Refresh token
POST http://localhost:8080/auth/token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncm9ndSIsImV4cCI6MTYxMzA2MzA0NiwiaWF0IjoxNjEyOTc2NjQ2fQ.k3u_MdbE6BSiELxtZ4z6cRlX8OnG9Mu7CnsjZujMC71QH4KIjRpTHBNCNtLSNnxu3i87YQesT-ovPh4ZfJn8dQ"
}


### Invalidate Refresh token
PUT http://localhost:8080/auth/token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncm9ndSIsImV4cCI6MTYxMzA2MzA0NiwiaWF0IjoxNjEyOTc2NjQ2fQ.k3u_MdbE6BSiELxtZ4z6cRlX8OnG9Mu7CnsjZujMC71QH4KIjRpTHBNCNtLSNnxu3i87YQesT-ovPh4ZfJn8dQ"
}

### Replace the current bearer by the token from previous request
GET http://localhost:8080/hello
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncm9ndSIsImV4cCI6MTYxMzA1ODMzOSwiaWF0IjoxNjEzMDQwMzM5fQ.yyN5hsjh1x3lOnKwNIE0x8qYc1AMlbEfVjg1bJG5GnOjGeDPD3N31k1J0ilUpTjlP_lDj4eb1x9-w1cwI6d4tQ

### Unauthorized
POST http://localhost:8080/test

### 