version: "3"

services:
  front:
    build: ./front
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./front/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  api:
    build: ./back
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/apidb
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: somepw

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: apidb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: somepw


