version: "3"

services:
  front:
    build: ./front
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - api
    volumes:
      - ./front/nginx:/server-confs
      - ./certs:/etc/letsencrypt
    environment:
      - SERVER_NAME=tezea.fleh.men
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes

  api:
    build: ./back
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/apidb
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: somepw

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: apidb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: somepw


